apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP   # Set the type to ClusterIP
  selector:
    app: multi-container   # Matches the labels of pods managed by the Deployment
  ports:
    - protocol: TCP
      port: 8089             # Port exposed by the Service
      targetPort: 80       # Port to which traffic will be forwarded on the pods
      # Port to which traffic will be forwarded on the pods

